matrix:
  default:
    dictionary: en_US
    files:
      - src/**/*.html
      - src/**/*.css
      - src/**/*.js
  wordlists:
    - words.txt
ignore-patterns:
  - "^https?://"
report:
  format: html # Example of report configuration
  output: spelling-report.html
