matrix:
  default:
    pipeline:
      - pyspelling.filters.html:
          - pyspelling.filters.html
        comments: false
        ignores:
          - code
          - pre
        sources:
          - "**/*.html"
language: en_US
  wordlist:
  wordlists:
    - words.txt
ignore-patterns:
  - "^https?://"
report:
  format: html # Example of report configuration
  output: spelling-report.html
