matrix:
  default:
    pipeline:
      - propelling.filters.html:
          sources: ["**/*.html"] # Example of HTML filter
      - pyspelling.filters.css:
          sources: ["**/*.css"] # Example of CSS filter
      - pyspelling.filters.js:
          sources: ["**/*.js"] # Example of JS filter
      - pyspelling.filters.markdown:
          sources: ["**/*.md"] # Example of Markdown filter
    language: en_US
    spelling:
    words lists:
      - words.txt
    ignore-patterns:
      - "^https?://"
    report:
      format: html # Example of report configuration
      output: spelling-report.html
