matrix:
  default:
    pipeline:
      - pyspelling.filters.html:HTMLFilter
    sources:
      - "**/*.html"
language: en_US
  wordlist:
  wordlists:
    - words.txt
ignore-patterns:
  - "^https?://"
report:
  format: html # Example of report configuration
  output: spelling-report.html
