matrix:
  default:
    pipeline:
      - pyspelling.filters.html:
          sources: ["**/*.html"]
      - pyspelling.filters.css:
          sources: ["**/*.css"]
      - pyspelling.filters.js:
          sources: ["**/*.js"]
      - pyspelling.filters.markdown:
          sources: ["**/*.md"] # Example of an additional filter
    language: en_US
    spelling:
      ignore-patterns:
        - "^https?://"
    report:
      format: html # Example of report configuration
      output: spelling-report.html
