matrix:
  default:
    pipeline:
      - pyspelling.filters.html:
      - pyspelling.filters.css:
      - pyspelling.filters.js:
    sources:
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
    language: en_US
    spelling:
      ignore-patterns:
        - "^https?://"
