name: Dependabot
on:
  workflow_run:
    workflows: ["Spellcheck Action"]
    types:
      - completed

  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
