name: Dependabot Workflow
on:
  workflow_run:
    workflows: ["Spellcheck Action"]
    types:
      - completed
  #push:
  #branches:
  #- main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
