# Basic dependabot.yml file
# REF: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot

on:
  push:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Enable version updates for Actions
        uses: actions/checkout@v2
      - name: Look for `.github/workflows` in the `root` directory
        run: echo "directory: .github/workflows"
      - name: Check for updates once a week
        run: echo "schedule: interval: weekly"