name: Spellcheck Action
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@v0
      with:
        sources: '**/*.html'
        default_encoding: utf-8
        spellcheck_args: >
          --lang=en_US
          --pipeline=pyspelling.filters.html
          --comments=false
          --ignore=code,pre,script
