name: Spellcheck Action
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  spellcheck:
    name: Check spelling with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sobolevn/misspell-fixer-action@master
        # - uses: peter-evans/create-pull-request@v7
        with:
          options: "-rsvn ."
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fixes by misspell-fixer"
          title: "Typos fix by misspell-fixer"
      # - name: Install misspell tool
      #   run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      # - name: Run misspell tool
      #   run: ./misspell -error *.html
