name: Spellcheck Action
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  spelling:
    name: Spellcheck with pyspelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyspelling
          # Install any additional libraries required: additional plugins, documentation building libraries, etc.
      - name: Install Aspell
        run: |
          sudo apt-get install -y aspell aspell-en
      - name: Build documents
        run: |
          echo "No documentation building required"
      - name: Spell check
        run: |
          python -m pyspelling
