name: Spellcheck Action
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  spellcheck:
    name: Check spelling with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install misspell tool
        run: wget -O - -q https://git.io/misspell | sh -s -- -b
      - name: Run misspell
        run: /usr/local/bin/misspell -error **/*.{html,md,txt}
