name: Spellcheck Action
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  spellcheck:
    name: Check spelling with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install misspell tool
        run: sudo apt-get update && sudo apt-get install -y misspell
      - name: Run misspell
        run: ./misspell -error **/*.{html,md,txt}
