name: Spellcheck Action
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  spellcheck:
    name: Check spelling with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install misspell tool
        run: |
          sudo apt-get update
          wget -qO- https://github.com/client9/misspell/releases/latest/download/misspell-linux-amd64.tar.gz | tar xz
          sudo mv misspell /usr/local/bin/
          - name: Set up Go environment
      - name: Run misspell
        run: /usr/local/bin/misspell -error **/*.{html,md,txt}
